# Generated by Django 5.1 on 2024-09-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='p_number',
            field=models.PositiveIntegerField(verbose_name='Número de la camiseta del jugador'),
        ),
    ]
