# Generated by Django 5.1 on 2024-09-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_players_p_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='p_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del jugador'),
        ),
        migrations.AlterField(
            model_name='players',
            name='p_second_last_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo apellido del jugador'),
        ),
        migrations.AlterField(
            model_name='players',
            name='p_second_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo nombre del jugador'),
        ),
        migrations.AlterField(
            model_name='technicalteam',
            name='t_second_last_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo apellido del integrante del ET'),
        ),
        migrations.AlterField(
            model_name='technicalteam',
            name='t_second_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo nombre del integrante del ET'),
        ),
    ]
